name: Run Calculation, Deploy and Commit.

# on:
#   push:
#     branches:
#       - test

on:
  schedule:
    - cron: '0 11 * * 5'
    # Run this job every Friday at 11 o'clock UTC.

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Insall dependencies
      - run: npm ci
      # Retrieve data and calculate fees
      - run: node index.js --ckey ${{ secrets.COVALENT_API_KEY }}

      # Deploy index.html to github pages
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      # Build multi-sig tx
      - run: node mstx.js -p ${{ secrets.PRIVATE_KEY_PANCAKE }} 
      # -t ${{ secrets.SLACK_TOKEN }} -s ${{ secrets.SLACK_SECRET }}

      # copy and commit this weeks fees
      - run: cp dist/index.json "data/$(date).json"
      - run: ls data
      - uses: EndBug/add-and-commit@v8
        with:
          add: '*.json --force'
          cwd: './data/'
          message: 'Commit Calculations'

  # Post notification to slack
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: PCS_Bot
        SLACK_ICON: https://effect.network/img/logo/logo_icon.png
        SLACK_MESSAGE: 'Updated Pancake Swap Fee Page: https://effectai.github.io/dao-pancake-fees/ :rocket: Please sign transaction: https://bloks.io/msig/pancakeffect/pcsefx'

