name: Run Calculation, Deploy and Commit.

on:
  push:
    branches:
      - test

# on:
#   schedule:
#     - cron: '0 10 * * 5'
#     # Run this job every Friday at 12 o'clock UTC.

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: node index.js --ckey ${{ secrets.COVALENT_API_KEY }}

      # - name: deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist

      - run: node src/mstx.js -p ${{ secrets.PRIVATE_KEY_PANCAKE }} 
      # -t ${{ secrets.SLACK_TOKEN }} -s ${{ secrets.SLACK_SECRET }}

      - run: cp dist/index.json "data/$(date).json"

      - name: Add & Commit
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Commit calculations"


  # slackNotification:
  #   name: Slack Notification
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Slack Notification
  #     uses: rtCamp/action-slack-notify@v2
  #     env:
  #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #       SLACK_USERNAME: PCS_Bot
  #       SLACK_ICON: https://effect.network/img/logo/logo_icon.png
  #       SLACK_MESSAGE: 'Updated Pancake Swap Fee Page: https://effectai.github.io/dao-pancake-fees/ :rocket: Please sign transaction: https://bloks.io/msig/pancakeffect/https://bloks.io/msig/pancakeffect/pancakefee'

